
" 行番号を表示
set number

" シンタックスハイライト
syntax enable
" カラーマップ
" colorscheme parabola

" カレント行ハイライト
set cursorline
" アンダーラインを引く(color terminal)
highlight CursorLine cterm=underline ctermfg=None ctermbg=None

" タイトルを表示
set title

" tab
set expandtab
set tabstop=4
set shiftwidth=4
"set smartindent
set cindent

" 移動コマンド
nnoremap <C-a> 0a
nnoremap <C-e> $a

" ターミナルを開く
set shell=zsh

nnoremap <C-@> :tab<Space>term<Return>
tnoremap <C-k> <C-w>gt
tnoremap <C-j> <C-w>gT
tnoremap <C-q> <C-c><C-d>

" タブ移動
nnoremap <C-k> gt
nnoremap <C-j> gT
nnoremap <C-t> :tabnew<Space>
nnoremap <C-q> :q<Return>

" 保存
nnoremap <C-s> :w<Return>
inoremap <C-s> <Esc>:w<Return>


" かっこの補完
" inoremap { {}<Left>
inoremap {<Enter> {}<Left><CR><ESC><S-o>
" inoremap ( ()<ESC>i
inoremap (<Enter> ()<Left><CR><ESC><S-o>
" inoremap [ []<ESC>i
inoremap [<Enter> []<Left><CR><ESC><S-o>

" クリップボードを連携
set clipboard+=unnamed

" insert-mode で移動できるように
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-h> <Left>
inoremap <C-l> <Right>

" 検索
set hlsearch
set incsearch
nnoremap  <Esc><Esc> :<C-u>nohlsearch<cr><Esc>

"ステータスライン
" ファイル名表示
set statusline=%F
" 変更チェック表示
set statusline+=%m
" 読み込み専用かどうか表示
set statusline+=%r
" ヘルプページなら[HELP]と表示
set statusline+=%h
" プレビューウインドウなら[Prevew]と表示
set statusline+=%w
" これ以降は右寄せ表示
set statusline+=%=
" file encoding
set statusline+=[ENC=%{&fileencoding}]
" 現在行数/全行数
set statusline+=[LOW=%l/%L]
" ステータスラインを常に表示(0:表示しない、1:2つ以上ウィンドウがある時だけ表示)
set laststatus=2


""""" 各言語の設定
""" Python
autocmd FileType python setl autoindent
autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd FileType python setl tabstop=8 expandtab shiftwidth=4 softtabstop=4

